import { UUID, DateString, Timestamp } from '../common';

/**
 * Base interface for a Project entity.
 */
export interface Project {
  project_id: UUID;
  name: string;
  description: string | null;
  start_date: DateString | null;
  end_date: DateString | null;
  status: string; // e.g., 'Draft', 'Active', 'Completed'
  workspace_id: UUID;
  created_by: UUID;
  created_at: Timestamp;
}

/**
 * DTO for creating a new Project.
 * project_id, created_by, and created_at are generated by the system.
 */
export interface CreateProjectDto {
  name: string;
  description?: string;
  start_date?: DateString;
  end_date?: DateString;
  status?: string;
  workspace_id: UUID;
}

/**
 * DTO for updating an existing Project.
 */
export interface UpdateProjectDto {
  name?: string;
  description?: string | null;
  start_date?: DateString | null;
  end_date?: DateString | null;
  status?: string;
}