import { UUID, Timestamp } from '../common';

/**
 * Base interface for a Task Status History entry.
 */
export interface TaskHistory {
  history_id: number; // BIGSERIAL
  task_id: UUID;
  changed_by: UUID;
  old_status: string | null;
  new_status: string;
  reason: string | null; // Required for 'Blocked' status
  timestamp: Timestamp;
}

/**
 * DTO for creating a new Task History entry (used internally by the service).
 * history_id and timestamp are generated by the system.
 */
export interface CreateTaskHistoryDto {
  task_id: UUID;
  changed_by: UUID;
  old_status?: string;
  new_status: string;
  reason?: string;
}