import { UUID, DateString, Timestamp } from '../common';

/**
 * Base interface for a Task entity.
 */
export interface Task {
  task_id: UUID;
  project_id: UUID;
  title: string;
  description: string | null;
  priority: string; // e.g., 'High', 'Medium', 'Low'
  due_date: DateString | null;
  assignee_id: UUID | null;
  status: string; // e.g., 'To Do', 'In Progress', 'Blocked', 'Done'
  created_at: Timestamp;
}

/**
 * DTO for creating a new Task.
 * task_id and created_at are generated by the system.
 */
export interface CreateTaskDto {
  project_id: UUID;
  title: string;
  description?: string;
  priority?: string;
  due_date?: DateString;
  assignee_id?: UUID;
  status?: string;
}

/**
 * DTO for updating an existing Task.
 */
export interface UpdateTaskDto {
  title?: string;
  description?: string | null;
  priority?: string;
  due_date?: DateString | null;
  assignee_id?: UUID | null;
  status?: string;
}