import { UUID, Timestamp } from '../common';

/**
 * Base interface for a Tag entity.
 */
export interface Tag {
  tag_id: UUID;
  name: string;
  color_hex: string | null;
  description: string | null;
  workspace_id: UUID;
  created_at: Timestamp;
}

/**
 * DTO for creating a new Tag.
 * tag_id and created_at are generated by the system.
 */
export interface CreateTagDto {
  name: string;
  color_hex?: string;
  description?: string;
  workspace_id: UUID;
}

/**
 * DTO for updating an existing Tag.
 */
export interface UpdateTagDto {
  name?: string;
  color_hex?: string | null;
  description?: string | null;
}