/**
 * Base interface for a Role entity.
 */
export interface Role {
  role_id: number; // SERIAL
  role_name: string; // 'Admin', 'PM', 'TM'
}

/**
 * DTO for creating a new Role.
 * role_id is generated by the system.
 */
export interface CreateRoleDto {
  role_name: string;
}

/**
 * DTO for updating an existing Role.
 */
export interface UpdateRoleDto {
  role_name?: string;
}