import { UUID, Timestamp } from '../common';

/**
 * Base interface for a User entity (excluding sensitive fields like password hash).
 */
export interface User {
  user_id: UUID;
  email: string;
  display_name: string;
  avatar_url: string | null;
  role_id: number;
  is_active: boolean;
  created_at: Timestamp;
}

/**
 * DTO for creating a new User.
 * user_id and created_at are generated by the system.
 */
export interface CreateUserDto {
  email: string;
  password_hash: string; // Required for creation
  display_name: string;
  avatar_url?: string;
  role_id: number;
  is_active?: boolean;
}

/**
 * DTO for updating an existing User.
 */
export interface UpdateUserDto {
  email?: string;
  password_hash?: string;
  display_name?: string;
  avatar_url?: string | null;
  role_id?: number;
  is_active?: boolean;
}