import { UUID, Timestamp } from '../common';

/**
 * Base interface for a User Audit Log entry.
 */
export interface UserAuditLog {
  log_id: number; // BIGSERIAL
  user_id: UUID;
  actor_id: UUID; // User who performed the action
  action_type: string; // e.g., 'ROLE_CHANGE', 'DEACTIVATION'
  details: Record<string, unknown>; // JSONB
  timestamp: Timestamp;
}

/**
 * DTO for creating a new User Audit Log entry (used internally by the service).
 * log_id and timestamp are generated by the system.
 */
export interface CreateUserAuditLogDto {
  user_id: UUID;
  actor_id: UUID;
  action_type: string;
  details: Record<string, unknown>;
}