import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./theme.scss";
import { Providers } from "./providers";
import { ThemeSwitcher } from "../components/ThemeSwitcher";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <div className="relative min-h-screen">
            <div className="absolute top-4 right-4 z-10">
              <ThemeSwitcher />
            </div>
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
